### ISSUE TITLE
Support for iPad

### ISSUE THREAD

**Issue by bcooley** [ianli/raphael-sketchpad#4]
I would like to suggest support for ipad.  Currently I have to modify the library to include checking for the ipad to get it to work.  Its exactly like checking for the iPod. 
Change the lines that include:
   agent.indexOf("iPhone") > 0 || agent.indexOf("iPod") > 0
to
   agent.indexOf("iPhone") > 0 || agent.indexOf("iPod") > 0 || agent.indexOf("iPad") > 0

this should enable the functionality on the iPad as well.

Thanks,
Ben

**Comment by gaucho1978** [comment]
when? why this is not implemented in the code that I downloaded?

**Comment by gaucho1978** [comment]
the taktran solution seems to be better cause it also includes android: https://github.com/taktran/raphael-sketchpad/commit/2e91f94967159ed67e64babd42deb6cf415a5bab

**Comment by gaucho1978** [comment]
some problems solved: https://github.com/gaucho1978/raphael-sketchpad/commit/fe1c43704473ddf571e0ec668a62c655f950bb9d

there was a bug related to offset() call that appears on chrome for android after a pinch. 
I solved it.
I also allowed the ability to pinch and pan with 2 fingers and to draw with one finger.
i also made some other minor changes. see them all on the link.
